---
title: "Policies"
date: "Updated `r Sys.Date()`"
---

In addition to [USF's institution-wide policies about disability access, religious observances, academic grievances, academic misconduct, and several other topics](https://www.usf.edu/provost/faculty/core-syllabus-policy-statements.aspx), this course adopts the following policies.

## Auditing Students

Auditing students are expected to complete all assessments (assignments, peer reviews, and participation). The difference between enrolling for credit is that auditing students are graded on each assignment on a pass/fail basis.

## Late Policy

A late submission is defined as any work, including participation, peer reviews, assignments, and projects, submitted after the deadline. For a late submission, the student will receive a 50% scaling of their grade for the first occurrence, and will receive a grade of 0 for subsequent occurrences. In all cases, late submissions past 24 hours will receive a zero.

## Academic Concession

I do not require a doctor's note or other documentation for necessary absences. A self-declaration will suffice -- [here](/concession_template.pdf) is a template you can use. Please submit this to the instructor. 

Whenever possible, if you will be absent, endeavor to submit assignments before their deadlines. If you need to submit an 
assignment late due to an absence, please contact me as soon as possible, and ideally before the absences.
If arrange to submit an assignment late, you may not be able to receive feedback from your peers.

## Plagiarism

Plagiarism, which is intellectual theft, occurs where an individual submits or presents the oral or written work of another person as his or her own and can include:

- multiple students submitting the same response
- copying from sources without citing them
- copying verbatim (word-for-word) from source and citing, but failing to make it explicit that this is a quotation (quotations should be used only rarely, if at all)

Plagiarism will not be tolerated in the MDS program and may result in dismissal from the program. Students are responsible for ensuring that any work submitted does not constitute plagiarism. Students who are in any doubt as to what constitutes plagiarism should consult their Instructor before handing in any assignments.

For more information see the [USF Academic Misconduct policies](https://www.usf.edu/provost/faculty/core-syllabus-policy-statements.aspx).

#### Code Plagiarism

Students must correctly cite any code that has been authored by someone else or by the student themselves for other assignments. Cases of code plagiarism may include, but are not limited to:

- the reproduction (copying and pasting) of code with none or minimal reformatting (e.g., changing the name of the variables)
- the translation of an algorithm or a script from a language to another
- the generation of code by automatic code-generations software

An “adequate acknowledgement” requires a detailed identification of the (parts of the) code reused and a full citation of the original source code that has been reused.
