---
title: "Participation Checklist"
date: "Updated `r Sys.Date()`"
---

# Participation Check List
 
Below you can find the check list with all the materials that need to be in your
participation repo to get full participation points. 

Instructor versions of the scripts run in class are provided for your reference.
 
 > Note that the instructor copy is just for your reference. You can't just copy-paste the code made by me and submit it as your participation. Please review the [Code Plagiarism](https://wiernik-datasci.netlify.com/policies/) guidelines to avoid plagiarism. 
 
0. **All classes**
    - [x] All folders (including the root, `tools`, `plotting`, etc.) must have a README.md file explaining what is in the folder
    
1. **Class Meeting 1a: Introduction to class and GitHub**   
    - [x] Register a GitHub account
    - [x] Share your username by filling out this [survey](https://usf.az1.qualtrics.com/jfe/form/SV_8kAdI0XraWU6geN)
    - [x] Create and populate `navigating_github.md` with several links
    
   **Class Meeting 1b: Introduction to R**   
    - [x] Provide the R script `s01_exploring_R.R` (or `cm002_R_exploration.R`) file. Instructor version can be found [here](https://github.com/bwiernik/DataSci-participation/blob/master/tools/s01_exploring_R.R)
    
2. **Class Meeting 2a RMarkdown**  
   - [x] Populate `navigating_github.md` document with some markdown features
   - [x] Convert the `.md` file into both `html` and add it to your repo
   - [x] Upload `rmd_exploration.Rmd` and its output formats (`md` and `html`)
   - [x] _Optional:_ Upload `rmd_exploration-slides.Rmd` both as `Rmd` and `html` formats
   
   **Class Meeting 2b The version control workflow**   
   - [x] Move all of the above files above into a folder called `tools` in your participation repo.
   
3. **Class Meeting 3 Intro to plotting with ggplot2**  
   - [x] Make a new `plotting` folder for these files.
   - [x] Complete the [s03a_ggplot_p1-exercise.Rmd](https://github.com/USF-Psych-DataSci/Classroom/raw/master/tutorials/s03a_ggplot_p1-exercise.Rmd) worksheet. 
     - A completed instructor version is available [here](https://github.com/bwiernik/DataSci-participation/blob/master/plotting/s03a_ggplot_p1-exercise.Rmd).
   - [x] Complete the [s03b_ggplot_p2-exercise.Rmd](https://raw.githubusercontent.com/USF-Psych-DataSci/Classroom/master/tutorials/s03b_ggplot_p2-exercise.Rmd) worksheet.
     - A completed instructor version is available [here](https://github.com/bwiernik/DataSci-participation/blob/master/plotting/s03b_ggplot_p2-exercise.Rmd).
   - [x] Submit `.Rmd` files and a knitted version of your choice (`md`, `html`, or `pdf` format).
   
4. **Class Meeting 4 Intro to data wrangling** 
   - [x] Make a new `wrangling` folder for these files.
   - [x] Complete the [s04a_data-wrangling_p1-exercise.Rmd](https://github.com/USF-Psych-DataSci/Classroom/raw/master/tutorials/s04a_data-wrangling_p1-exercise.Rmd) worksheet.
     - A completed instructor version is available [here](https://github.com/bwiernik/DataSci-participation/blob/master/wrangling/s04a_data-wrangling_p1-exercise.Rmd).
   - [x] Complete the [s04b_data-wrangling_p2-exercise.Rmd](https://github.com/USF-Psych-DataSci/Classroom/raw/master/tutorials/v) worksheet. 
     - A completed instructor version is available [here](https://github.com/bwiernik/DataSci-participation/blob/master/wrangling/s04b_data-wrangling_p2-exercise.Rmd)
   - [x] Submit `.Rmd` files and a knitted version of your choice (`md`, `html`, or `pdf` format).

