---
title: "Data Science and Programming Assignment 05: Preparing your project folder"
---

__Due March 9, 2020 at 23:59__

## Objective

In this assignment, you are going to think about your final project for the class
and do the setup 

You have learned alot about data wrangling! You know how to use the tidyverse to:

* Filter rows and select variables in a principled or name-based manner
* Modify variables and create new variables
* Group rows of a data frame and do summarizing or mutating computations within group
* Reshape a data frame
* Get new information into a data frame via a joining

The goal of this homework is to solidify your data wrangling skills by working 
some realistic problems in the grey area between data aggregation and data 
reshaping.

If you internalize that there are multiple solutions to most problems, you will 
spend less time banging your head against the wall in data analysis. If 
something's really hard, sneak up on it from a different angle.

## Tidy Submission (20%)

### Mechanics (15%)

Follow the instructions for making a tidy submission, found on the 
[assignments home page](evaluation/assignments).

**The requirement about having a README.md file that explains the content of this folder will super important here! Don't just say "This is Homework 5." Tell me what sort of data you have, where you got it, what the folders are, etc.**

### Writing (5%)

- You must use clear English, spelling, and grammar.
- You should write concisely. 

## Step 1: Set up your folder structure (20%)

In your homework repo, create a `final_project` folder. Prepare your folder 
structure inside this folder for your final project. Folders and files you
should probably include in this folder structure are:
  
  - An RStudio Project .Rproj file in the folder root
  - A `data` folder that holds the relevant data files for the project
    - Could also have separate `data-raw` and `data` folders
  - A `markdown` folder that will hold your RMarkdown manuscripts
  - An `output` folder that will hold your output files
    - Depending on how many figures and other output files you may have, 
      you might want to split/subfolder this into `figures`, `reports`, etc.
  - Other subfolders as needed, e.g.:
    - `admin` for adminstrative documents (e.g., IRB approval, grant information)
    - `doc` for documentation (e.g., variable codebooks), 
    - `scripts` or `src` or `R` as a place to store functions and scripts that 
      you call from your markdown (e.g., a data import and cleaning script)
      
All of these folders should be described in your README.md file for this project.

## Step 2: Find, download, and document a dataset (40%)

In this step, you need to identify a dataset you want to work with for your
final project. Some potential sources for datasets include:

  - [ICPSR](https://www.icpsr.umich.edu/icpsrweb/)
  - [Google Datasets](https://www.blog.google/products/search/discovering-millions-datasets-web/)
  - [Harvard Dataverse](https://dataverse.harvard.edu/)
  - [FiveThirtyEight's GitHub repos](https://github.com/fivethirtyeight/data)
  - Data from your own research work or experience
  
The requirements for this dataset:
  - It cannot be already available as an R package like `gapminder`, `nycflights13`,
    or one of the datasets in `datasets`
    - It's okay if there is any R package you use to download the data, such as
      `rtweet`, so long as it isn't already a neatly packaged dataset for you.
  - Ideally, it should be a dataset that needs some cleaning, reshaping, wrangling
    before it's ready for analysis
  
Talk to me if you are having trouble finding an interesting or suitable dataset!

Once you have identified a dataset, download it and place it in your `data` folder.
  - If this is data you are downloading from the internet, write and run a
    .R script to download the dataset
    - Hint: Try to write this as a separate .R file from your homework .Rmd file
      and call it in your .Rmd using `source()`.
  - If you are working with data from your own research work, you can place it
    directly in the folder
    - If the files are hosted somewhere online, on another server, or elsewhere,
      write a .R script to retrieve them, as described above.
  - Your data file should have a useful descriptve name (no `data.xlsx`!). It
    should include:
    - A description of the file (e.g., "gapminder-data-all-countries")
    - A date in a sortable format (e.g., "2020-03-04")
    - No spaces

Document your data. Describe the key variables, their types (e.g., character, 
integrer, numeric), their possible values (e.g., for a personality item, maybe 
integers from 1-5), etc. Describe how missing data is indicated (blank cells, 
"NA", "-999", etc.). This documentation could be in the main project README.md
file or in a README.md or other .md file in the `data` folder.


## Step 3: Practice input, process, output (40%)

In your .Rmd file for this homework assignment, practice reading your data file
into R, processing the imported data, and outputting files. Import your file
using R functions (not the buttons in RStudio). You will want to output two things:

  1. A data file, such as cleaned dataset or a summarized dataset/table
  2. A plot, in several formats, including (1) a bitmap format, (2) a vector 
     format, and (3) PDF
  
While your processing and plot should be useful, 
**you don't have to do the entire final project now**! The point of this 
exercise is to practice reading your files into R, working with them, and then
saving your outputs to disk (other than/in addition to the files that are output
when you knit a .Rmd file).

Save your data file and plots to your `output` folder (or other more specific folders
if that is your structure). Be sure to use descriptive file names and document
what these files are with a .md file.

Save your data file using `write_csv()` or a similar function. Save you images
using `ggsave()`. Do not use the buttons in RStudio.
