---
title: "Assignment 01: Tools for data analytic work"
---

## Objective

This assignment was designed to give you practice with the tools discussed in the first two weeks: R, (R)Markdown, and GitHub. You'll be:

- Developing of a simple repository with GitHub;
- Authoring in Markdown and RMarkdown
- Coding in R through data exploration
- Generating output from (`.Rmd`) source using RStudio.

As you work on the assignment, use the workflow we talked about in class:

- Pull from GitHub.
- Make changes locally to local files. Use the Preview/Knit button in RMarkdown to see what your Markdown will look like when rendered.
- Save your changes.
- Commit your changes to your repo.
- Push the commit to GitHub.

## Tidy Submission (20%)

Follow the instructions for making a tidy submission, found on the [assignments home page](/evaluation/assignments).

Note: Usually, a tidy submission does not have this much weight, but I know that this part is not trivial for your first time. A tidy submission involves using the tools taught in Week 1, and this is what this assignment is all about.

## Writing (5%)

- You must use clear writing, spelling, and grammar.
- Your writing is concise. 

## Exercise 1: Edit `README.md` (40%)

---

Rubrics: 

- Accuracy: (20%)
	- Does your markdown render properly, or are there mistakes like _this__ or (this)[www.example.com]?
- Completeness: (20%)
	- Did you include at least five markdown features in your README? (= 4% each)

---

Your task here is to edit the main `README.md` file in your repository. It should contain the following:

1. The beginning of the README should contain a very brief description as to what the repository is (a sentence or two), so that an unknowing visitor landing on the repository can orient themselves. You should also help the visitor navigate your repository (in whatever way you think is most appropriate). 
2. Then, introduce yourself briefly. 

When writing your README, be sure to showcase at least five functionalities of GitHub-flavored markdown. The [markdown cheatsheet](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf) might help here, or, the *Help* menu in RStudio will bring up a Markdown Quick Reference at any time.

Here's a [sample readme file](https://github.com/USF-Psych-DataSci/DataSci-home/blob/master/content/evaluation/hw01/sample_readme.md) that goes way above and beyond what I'm looking for (aside from describing the repo).

## Exercise 2: RMarkdown for Dataset exploration (35%)

---

Rubrics:

- Accuracy: (20%)
	- Did you use at least three functions?
	- Given that you did, does your code run error-free?
- Reasoning: (15%)
	- Does your exploration showcase the dataset?

---

Make an R Markdown document that explores a dataset, such as `palmerpenguins::penguins`, `gapminder::gapminder`, or `psych::bfi` seen in class. 
You don't need an extensive exploration here. 
You just need enough to show someone reading your report some of the features of the dataset beyond just printing it to screen. 

For example, what is the general structure of the dataset? 
How many rows does it have? How many colums? 
What are the descriptive statistics for some of the important variables?

You should demonstrate the use of at least three functions.

Don't forget! 
Your "tidy submission" marks relies on you rendering your RMarkdown file to **both** the `github_document` and `html_document` output formats. 
Commit all three of the `.Rmd`, `.html`, and `.md` files and push them to GitHub. 

Give this a decent name, such as `hw01_exploring_data.Rmd` (which will produce output files, `hw01_exploring_data.md` and `hw01_exploring_data.html`). 
These files should also be in a folder called something like `hw01`.
